/*------------------------------------------------------------------------------
<auto-generated>
	This code was generated from the Mapper template.
	Manual changes to this file may cause unexpected behavior in your application.
	Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
#nullable enable
namespace Btms.Types.Alvs.Mapping;

public static class AlvsClearanceRequestMapper
{
	public static Btms.Model.Alvs.AlvsClearanceRequest? Map(Btms.Types.Alvs.AlvsClearanceRequest? from)
	{
		if (from == default) return default;

		var to = new Btms.Model.Alvs.AlvsClearanceRequest ();
        to.ServiceHeader = ServiceHeaderMapper.Map(from.ServiceHeader);
        to.Header = HeaderMapper.Map(from.Header);
        to.Items = from.Items?.Select(x => ItemsMapper.Map(x)).Where(x => x != null).ToArray()!;
		return to;
	}
}
