//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Btms.Types.Alvs.Mapping;

public static class DocumentMapper
{
    public static Btms.Model.Cds.Document Map(Btms.Types.Alvs.Document from)
    {
        if (from is null)
        {
            return default!;
        }
        var to = new Btms.Model.Cds.Document();
        to.DocumentCode = from.DocumentCode;
        to.DocumentReference = from.DocumentReference;
        to.DocumentStatus = from.DocumentStatus;
        to.DocumentControl = from.DocumentControl;
        to.DocumentQuantity = from.DocumentQuantity;
        return to;
    }
}