//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


using Btms.Model.Cds;

namespace Btms.Types.Alvs.Mapping;

public static class FinalisationMapper
{
    public static Btms.Model.Cds.CdsFinalisation Map(Btms.Types.Alvs.Finalisation from)
    {
        if (from is null)
        {
            return default!;
        }

        var to = new Btms.Model.Cds.CdsFinalisation()
        {
            ServiceHeader = ServiceHeaderMapper.Map(from.ServiceHeader!),
            Header = new Model.Cds.FinalisationHeader()
            {
                DecisionNumber = from.Header.DecisionNumber,
                EntryReference = from.Header.EntryReference,
                EntryVersionNumber = from.Header.EntryVersionNumber,
                FinalState = (FinalState)int.Parse(from.Header.FinalState),
                ManualAction = from.Header.ManualAction == "Y"
            }
        };
        
        return to;
    }
}


