//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Btms.Types.Gvms.Mapping;

public static class PlannedCrossingMapper
{
    public static Btms.Model.Gvms.PlannedCrossing Map(Btms.Types.Gvms.PlannedCrossing from)
    {
        if (from is null)
        {
            return default!;
        }
        var to = new Btms.Model.Gvms.PlannedCrossing();
        to.RouteId = from.RouteId;
        to.DepartsAt = from.DepartsAt;
        return to;
    }
}