//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class ChedppNotAcceptableReasonCommodityOrPackageEnumMapper
{
    public static Btms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum? Map(Btms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.C => Btms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.C,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.P => Btms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.P,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.Cp => Btms.Model.Ipaffs.ChedppNotAcceptableReasonCommodityOrPackageEnum.Cp,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}