//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class ChedppNotAcceptableReasonReasonEnumMapper
{
    public static Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum? Map(Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdm => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdm,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdii => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPhmdii,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPa => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPa,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPic => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPic,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPill => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPill,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPed => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPed,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPmod => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPmod,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPfi => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPfi,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPnol => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPnol,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPcne => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPcne,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadm => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadm,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadi => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPadi,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPpni => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPpni,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPf => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPf,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPo => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocPo,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcevd => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcevd,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqefi => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqefi,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqebec => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcpqebec,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcts => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNcts,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNco => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocNco,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrii => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrii,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrsr => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.DocOrsr,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OriOrrnu => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OriOrrnu,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrpp => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrpp,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrho => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrho,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyIs => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyIs,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrsr => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.PhyOrsr,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthCnl => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthCnl,
            Btms.Types.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthO => Btms.Model.Ipaffs.ChedppNotAcceptableReasonReasonEnum.OthO,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}