//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class CommoditiesCommodityIntendedForEnumMapper
{
    public static Btms.Model.Ipaffs.CommoditiesCommodityIntendedForEnum? Map(Btms.Types.Ipaffs.CommoditiesCommodityIntendedForEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.CommoditiesCommodityIntendedForEnum.Human => Btms.Model.Ipaffs.CommoditiesCommodityIntendedForEnum.Human,
            Btms.Types.Ipaffs.CommoditiesCommodityIntendedForEnum.Feedingstuff => Btms.Model.Ipaffs.CommoditiesCommodityIntendedForEnum.Feedingstuff,
            Btms.Types.Ipaffs.CommoditiesCommodityIntendedForEnum.Further => Btms.Model.Ipaffs.CommoditiesCommodityIntendedForEnum.Further,
            Btms.Types.Ipaffs.CommoditiesCommodityIntendedForEnum.Other => Btms.Model.Ipaffs.CommoditiesCommodityIntendedForEnum.Other,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}