//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class CommodityRiskResultPhsiDecisionEnumMapper
{
public static Btms.Model.Ipaffs.CommodityRiskResultPhsiDecisionEnum? Map(Btms.Types.Ipaffs.CommodityRiskResultPhsiDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Btms.Types.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Required => Btms.Model.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Required,
    Btms.Types.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Notrequired => Btms.Model.Ipaffs.CommodityRiskResultPhsiDecisionEnum.Notrequired,

    _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
};
}
        

}


