/*------------------------------------------------------------------------------
<auto-generated>
    This code was generated from the EnumMapper template.
    Manual changes to this file may cause unexpected behavior in your application.
    Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class ConsignmentCheckPhysicalCheckNotDoneReasonEnumMapper
{
    public static Btms.Model.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum? Map(Btms.Types.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum? from)
    {
        if (from == default) return default;

        return from switch
        {
            Btms.Types.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum.ReducedChecksRegime => Btms.Model.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum.ReducedChecksRegime,
            Btms.Types.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum.Other => Btms.Model.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum.Other,
            _ => throw new ArgumentOutOfRangeException(nameof(from), from, "Unable to map enum ConsignmentCheckPhysicalCheckNotDoneReasonEnum value Btms.Types.Ipaffs.ConsignmentCheckPhysicalCheckNotDoneReasonEnum")
        };
    }
}
