/*------------------------------------------------------------------------------
<auto-generated>
    This code was generated from the EnumMapper template.
    Manual changes to this file may cause unexpected behavior in your application.
    Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class DecisionNotAcceptableActionQuarantineImposedReasonEnumMapper
{
    public static Btms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum? Map(Btms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum? from)
    {
        if (from == default) return default;

        return from switch
        {
            Btms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts => Btms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts,
            Btms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart => Btms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart,
            Btms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial => Btms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial,
            Btms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.Other => Btms.Model.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum.Other,
            _ => throw new ArgumentOutOfRangeException(nameof(from), from, "Unable to map enum DecisionNotAcceptableActionQuarantineImposedReasonEnum value Btms.Types.Ipaffs.DecisionNotAcceptableActionQuarantineImposedReasonEnum")
        };
    }
}
