//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class DecisionFreeCirculationPurposeEnumMapper
{
    public static Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum? Map(Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.AnimalFeedingStuff => Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.AnimalFeedingStuff,
            Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.HumanConsumption => Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.HumanConsumption,
            Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.PharmaceuticalUse => Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.PharmaceuticalUse,
            Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.TechnicalUse => Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.TechnicalUse,
            Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.FurtherProcess => Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.FurtherProcess,
            Btms.Types.Ipaffs.DecisionFreeCirculationPurposeEnum.Other => Btms.Model.Ipaffs.DecisionFreeCirculationPurposeEnum.Other,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}