//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class ExternalReferenceSystemEnumMapper
{
    public static Btms.Model.Ipaffs.ExternalReferenceSystemEnum? Map(Btms.Types.Ipaffs.ExternalReferenceSystemEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.ExternalReferenceSystemEnum.Ecert => Btms.Model.Ipaffs.ExternalReferenceSystemEnum.Ecert,
            Btms.Types.Ipaffs.ExternalReferenceSystemEnum.Ephyto => Btms.Model.Ipaffs.ExternalReferenceSystemEnum.Ephyto,
            Btms.Types.Ipaffs.ExternalReferenceSystemEnum.Enotification => Btms.Model.Ipaffs.ExternalReferenceSystemEnum.Enotification,
            Btms.Types.Ipaffs.ExternalReferenceSystemEnum.Ncts => Btms.Model.Ipaffs.ExternalReferenceSystemEnum.Ncts,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}