//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class ImportNotificationTypeEnumMapper
{
    public static Btms.Model.Ipaffs.ImportNotificationTypeEnum? Map(Btms.Types.Ipaffs.ImportNotificationTypeEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.ImportNotificationTypeEnum.Cveda => Btms.Model.Ipaffs.ImportNotificationTypeEnum.Cveda,
            Btms.Types.Ipaffs.ImportNotificationTypeEnum.Cvedp => Btms.Model.Ipaffs.ImportNotificationTypeEnum.Cvedp,
            Btms.Types.Ipaffs.ImportNotificationTypeEnum.Chedpp => Btms.Model.Ipaffs.ImportNotificationTypeEnum.Chedpp,
            Btms.Types.Ipaffs.ImportNotificationTypeEnum.Ced => Btms.Model.Ipaffs.ImportNotificationTypeEnum.Ced,
            Btms.Types.Ipaffs.ImportNotificationTypeEnum.Imp => Btms.Model.Ipaffs.ImportNotificationTypeEnum.Imp,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}