//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class InspectionCheckTypeEnumMapper
{
    public static Btms.Model.Ipaffs.InspectionCheckTypeEnum? Map(Btms.Types.Ipaffs.InspectionCheckTypeEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.InspectionCheckTypeEnum.PhsiDocument => Btms.Model.Ipaffs.InspectionCheckTypeEnum
                .PhsiDocument,
            Btms.Types.Ipaffs.InspectionCheckTypeEnum.PhsiIdentity => Btms.Model.Ipaffs.InspectionCheckTypeEnum
                .PhsiIdentity,
            Btms.Types.Ipaffs.InspectionCheckTypeEnum.PhsiPhysical => Btms.Model.Ipaffs.InspectionCheckTypeEnum
                .PhsiPhysical,
            Btms.Types.Ipaffs.InspectionCheckTypeEnum.Hmi => Btms.Model.Ipaffs.InspectionCheckTypeEnum.Hmi,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}