//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class JourneyRiskCategorisationResultRiskLevelMethodEnumMapper
{
    public static Btms.Model.Ipaffs.JourneyRiskCategorisationResultRiskLevelMethodEnum? Map(
        Btms.Types.Ipaffs.JourneyRiskCategorisationResultRiskLevelMethodEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.JourneyRiskCategorisationResultRiskLevelMethodEnum.System => Btms.Model.Ipaffs
                .JourneyRiskCategorisationResultRiskLevelMethodEnum.System,
            Btms.Types.Ipaffs.JourneyRiskCategorisationResultRiskLevelMethodEnum.User => Btms.Model.Ipaffs
                .JourneyRiskCategorisationResultRiskLevelMethodEnum.User,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}