//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class LaboratoryTestResultConclusionEnumMapper
{
    public static Btms.Model.Ipaffs.LaboratoryTestResultConclusionEnum? Map(
        Btms.Types.Ipaffs.LaboratoryTestResultConclusionEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.LaboratoryTestResultConclusionEnum.Satisfactory => Btms.Model.Ipaffs
                .LaboratoryTestResultConclusionEnum.Satisfactory,
            Btms.Types.Ipaffs.LaboratoryTestResultConclusionEnum.NotSatisfactory => Btms.Model.Ipaffs
                .LaboratoryTestResultConclusionEnum.NotSatisfactory,
            Btms.Types.Ipaffs.LaboratoryTestResultConclusionEnum.NotInterpretable => Btms.Model.Ipaffs
                .LaboratoryTestResultConclusionEnum.NotInterpretable,
            Btms.Types.Ipaffs.LaboratoryTestResultConclusionEnum.Pending => Btms.Model.Ipaffs
                .LaboratoryTestResultConclusionEnum.Pending,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}