//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class PartThreeControlStatusEnumMapper
{
    public static Btms.Model.Ipaffs.PartThreeControlStatusEnum? Map(Btms.Types.Ipaffs.PartThreeControlStatusEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.PartThreeControlStatusEnum.Required => Btms.Model.Ipaffs.PartThreeControlStatusEnum
                .Required,
            Btms.Types.Ipaffs.PartThreeControlStatusEnum.Completed => Btms.Model.Ipaffs.PartThreeControlStatusEnum
                .Completed,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}


