//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class PartOneTypeOfImpEnumMapper
{
    public static Btms.Model.Ipaffs.PartOneTypeOfImpEnum? Map(Btms.Types.Ipaffs.PartOneTypeOfImpEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.PartOneTypeOfImpEnum.A => Btms.Model.Ipaffs.PartOneTypeOfImpEnum.A,
            Btms.Types.Ipaffs.PartOneTypeOfImpEnum.P => Btms.Model.Ipaffs.PartOneTypeOfImpEnum.P,
            Btms.Types.Ipaffs.PartOneTypeOfImpEnum.D => Btms.Model.Ipaffs.PartOneTypeOfImpEnum.D,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}


