//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class PartyTypeEnumMapper
{
    public static Btms.Model.Ipaffs.PartyTypeEnum? Map(Btms.Types.Ipaffs.PartyTypeEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.PartyTypeEnum.CommercialTransporter => Btms.Model.Ipaffs.PartyTypeEnum
                .CommercialTransporter,
            Btms.Types.Ipaffs.PartyTypeEnum.PrivateTransporter => Btms.Model.Ipaffs.PartyTypeEnum.PrivateTransporter,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}