//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class PartOneStoreTransporterContactEnumMapper
{
    public static Btms.Model.Ipaffs.PartOneStoreTransporterContactEnum? Map(Btms.Types.Ipaffs.PartOneStoreTransporterContactEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.PartOneStoreTransporterContactEnum.Yes => Btms.Model.Ipaffs.PartOneStoreTransporterContactEnum.Yes,
            Btms.Types.Ipaffs.PartOneStoreTransporterContactEnum.No => Btms.Model.Ipaffs.PartOneStoreTransporterContactEnum.No,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}