//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class PurposePurposeGroupEnumMapper
{
    public static Btms.Model.Ipaffs.PurposePurposeGroupEnum? Map(Btms.Types.Ipaffs.PurposePurposeGroupEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForImport => Btms.Model.Ipaffs.PurposePurposeGroupEnum.ForImport,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForNONConformingConsignments => Btms.Model.Ipaffs
                .PurposePurposeGroupEnum.ForNONConformingConsignments,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForTranshipmentTo => Btms.Model.Ipaffs.PurposePurposeGroupEnum
                .ForTranshipmentTo,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForTransitTo3rdCountry => Btms.Model.Ipaffs
                .PurposePurposeGroupEnum.ForTransitTo3rdCountry,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForReImport => Btms.Model.Ipaffs.PurposePurposeGroupEnum
                .ForReImport,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForPrivateImport => Btms.Model.Ipaffs.PurposePurposeGroupEnum
                .ForPrivateImport,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForTransferTo => Btms.Model.Ipaffs.PurposePurposeGroupEnum
                .ForTransferTo,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForImportReConformityCheck => Btms.Model.Ipaffs
                .PurposePurposeGroupEnum.ForImportReConformityCheck,
            Btms.Types.Ipaffs.PurposePurposeGroupEnum.ForImportNonInternalMarket => Btms.Model.Ipaffs
                .PurposePurposeGroupEnum.ForImportNonInternalMarket,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}