//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class ResultEnumMapper
{
    public static Btms.Model.Ipaffs.ResultEnum? Map(Btms.Types.Ipaffs.ResultEnum? from)
    {
        if (from == null)
        {
            return default!;
        }

        return from switch
        {
            Btms.Types.Ipaffs.ResultEnum.Satisfactory => Btms.Model.Ipaffs.ResultEnum.Satisfactory,
            Btms.Types.Ipaffs.ResultEnum.SatisfactoryFollowingOfficialIntervention => Btms.Model.Ipaffs.ResultEnum
                .SatisfactoryFollowingOfficialIntervention,
            Btms.Types.Ipaffs.ResultEnum.NotSatisfactory => Btms.Model.Ipaffs.ResultEnum.NotSatisfactory,
            Btms.Types.Ipaffs.ResultEnum.NotDone => Btms.Model.Ipaffs.ResultEnum.NotDone,
            Btms.Types.Ipaffs.ResultEnum.Derogation => Btms.Model.Ipaffs.ResultEnum.Derogation,
            Btms.Types.Ipaffs.ResultEnum.NotSet => Btms.Model.Ipaffs.ResultEnum.NotSet,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}