//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Btms.Types.Ipaffs.Mapping;

public static class TemperatureEnumMapper
{
    public static Btms.Model.Ipaffs.TemperatureEnum? Map(Btms.Types.Ipaffs.TemperatureEnum? from)
    {
        if (from == null)
        {
            return default!;
        }
        return from switch
        {
            Btms.Types.Ipaffs.TemperatureEnum.Ambient => Btms.Model.Ipaffs.TemperatureEnum.Ambient,
            Btms.Types.Ipaffs.TemperatureEnum.Chilled => Btms.Model.Ipaffs.TemperatureEnum.Chilled,
            Btms.Types.Ipaffs.TemperatureEnum.Frozen => Btms.Model.Ipaffs.TemperatureEnum.Frozen,

            _ => throw new ArgumentOutOfRangeException(nameof(from), from, null)
        };
    }


}