//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;
using Btms.Model.Auditing;
using Btms.Model.Ipaffs;
using MongoDB.Bson.Serialization.Attributes;


namespace Btms.Model.Cds;

public partial class ItemCheck
{
    [Attr]
    [System.ComponentModel.Description("")]
    public int ItemNumber { get; set; }
    
    [Attr]
    [System.ComponentModel.Description("")]
    public required string CheckCode { get; set; }
    
    [Attr]
    [System.ComponentModel.Description("")]
    public required string AlvsDecisionCode { get; set; }

    [Attr]
    [System.ComponentModel.Description("")]
    public string? BtmsDecisionCode { get; set; }
}

public class DecisionImportNotifications
{
    public required string Id { get; set; }
    public required int? Version { get; set; }
    public required DateTime Created { get; set; }
    public required DateTime Updated { get; set; }
    public required DateTime CreatedSource { get; set; }
    public required DateTime UpdatedSource { get; set; }
}

public class StatusChecker
{

    [Attr]
    [System.ComponentModel.Description("")]
    public bool AllMatch { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AnyMatch { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AllNoMatch { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AnyNoMatch { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AllHold { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AnyHold { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AllRefuse { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AnyRefuse { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AllRelease { get; set; } = default;
        
    [Attr]
    [System.ComponentModel.Description("")]
    public bool AnyRelease { get; set; } = default;
}

public class MovementStatus
{
    public static MovementStatus Default()
    {
        return new MovementStatus() { ChedTypes = [] };
    }
    
    [Attr]
    [System.ComponentModel.Description("")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public required ImportNotificationTypeEnum[]? ChedTypes { get; set; }

    [Attr]
    [System.ComponentModel.Description("")]
    public string LinkStatus { get; set; } = "Not Linked";

}
public partial class DecisionContext : IAuditContext //
{
    //TODO : Remove in favour of MovementStatus
    [Attr]
    [System.ComponentModel.Description("")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public ImportNotificationTypeEnum[]? ChedTypes { get; set; }
    
    [Attr]
    [System.ComponentModel.Description("")]
    public List<DecisionImportNotifications>? ImportNotifications { get; set; }
    
    [Attr]
    [System.ComponentModel.Description("")]
    public int AlvsDecisionNumber { get; set; } = default;
    
    [Attr]
    [System.ComponentModel.Description("")]
    public int BtmsDecisionNumber { get; set; } = default;
    
    [Attr]
    [System.ComponentModel.Description("")]
    public int EntryVersionNumber { get; set; } = default;
    
    [Attr]
    [System.ComponentModel.Description("")]
    public bool Paired { get; set; } = default;
    
    [Attr]
    [System.ComponentModel.Description("")]
    public string? DecisionStatus { get; set; }
    
    [Attr]
    [System.ComponentModel.Description("")]
    public bool DecisionMatched { get; set; } = default;
    
    [Attr]
    [System.ComponentModel.Description("")]
    public StatusChecker? AlvsCheckStatus { get; set; }
    
    [Attr]
    [System.ComponentModel.Description("")]
    public StatusChecker? BtmsCheckStatus { get; set; }
}

public partial class AlvsDecisionStatus  //
{
    [Attr]
    [System.ComponentModel.Description("")]
    public List<AlvsDecision> Decisions { get; set; } = new List<AlvsDecision>();

    [Attr]
    [System.ComponentModel.Description("")]
    public string? DecisionStatus { get; set; } = default;
    
    [Attr]
    [System.ComponentModel.Description("")]
    public DecisionContext Context { get; set; } = new DecisionContext();
    
    // TODO - should we put the checks into context, and so into audit log?
    [Attr]
    [System.ComponentModel.Description("")]
    public List<ItemCheck> Checks { get; set; } = new List<ItemCheck>();
}

public partial class AlvsDecision  //
{
    [Attr]
    [System.ComponentModel.Description("")]
    public required CdsClearanceRequest Decision { get; set; }

    [Attr]
    [System.ComponentModel.Description("")]
    public required DecisionContext Context { get; set; }
    
    // TODO - should we put the checks into context, and so into audit log?
    [Attr]
    [System.ComponentModel.Description("")]
    public required List<ItemCheck> Checks { get; set; }
    
}


