//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Model.Cds;

/// <summary>
/// Message sent to the server to send an ALVSClearanceRequest.
/// </summary>
public partial class CdsClearanceRequestPost  //
{

    [Attr]
    [JsonPropertyName("xmlSchemaVersion")]
    public string? XmlSchemaVersion { get; set; }

    [Attr]
    [JsonPropertyName("userIdentification")]
    public string? UserIdentification { get; set; }

    [Attr]
    [JsonPropertyName("userPassword")]
    public string? UserPassword { get; set; }

    [Attr]
    [JsonPropertyName("sentOn")]
    public DateTime? SentOn { get; set; }

    [Attr]
    [JsonPropertyName("alvsClearanceRequest")]
    public CdsClearanceRequest? AlvsClearanceRequest { get; set; }

}