//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Model.Cds;
public partial class Check  //
{

    [Attr]
    [JsonPropertyName("checkCode")]
    public string? CheckCode { get; set; }

    [Attr]
    [JsonPropertyName("departmentCode")]
    public string? DepartmentCode { get; set; }

    [Attr]
    [JsonPropertyName("decisionCode")]
    public string? DecisionCode { get; set; }

    [Attr]
    [JsonPropertyName("decisionsValidUntil")]
    public DateTime? DecisionsValidUntil { get; set; }

    [Attr]
    [JsonPropertyName("decisionReasons")]
    public string[]? DecisionReasons { get; set; }

}