//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Model.Cds;

/// <summary>
/// Seperates the items that are on Clearance Requests from the internal model items, and decision items
/// Might be a good idea to have the generator generate this in time.
/// </summary>
public partial class ClearanceRequestItems  //
{
    public List<string> GetIdentifiers()
    {
        var list = new HashSet<string>();
        if (Documents != null)
        {
            foreach (var itemDocument in Documents)
            {
                if (MatchIdentifier.TryFromCds(itemDocument.DocumentReference!, out var identifier))
                {
                    list.Add(identifier.Identifier);
                }
            }
        }

        return list.ToList();
    }

    [Attr]
    [JsonPropertyName("itemNumber")]
    public int? ItemNumber { get; set; }

    [Attr]
    [JsonPropertyName("customsProcedureCode")]
    public string? CustomsProcedureCode { get; set; }

    [Attr]
    [JsonPropertyName("taricCommodityCode")]
    public string? TaricCommodityCode { get; set; }

    [Attr]
    [JsonPropertyName("goodsDescription")]
    public string? GoodsDescription { get; set; }

    [Attr]
    [JsonPropertyName("consigneeId")]
    public string? ConsigneeId { get; set; }

    [Attr]
    [JsonPropertyName("consigneeName")]
    public string? ConsigneeName { get; set; }

    [Attr]
    [JsonPropertyName("itemNetMass")]
    public decimal? ItemNetMass { get; set; }

    [Attr]
    [JsonPropertyName("itemSupplementaryUnits")]
    public decimal? ItemSupplementaryUnits { get; set; }

    [Attr]
    [JsonPropertyName("itemThirdQuantity")]
    public decimal? ItemThirdQuantity { get; set; }

    [Attr]
    [JsonPropertyName("itemOriginCountryCode")]
    public string? ItemOriginCountryCode { get; set; }

    [Attr]
    [JsonPropertyName("documents")]
    public Document[]? Documents { get; set; }

    [Attr]
    [JsonPropertyName("checks")]
    public ClearanceRequestCheck[]? Checks { get; set; }

}

/// <summary>
/// Seperates the checks that are on Clearance Requests from the internal model items, and decision checks
/// Might be a good idea to have the generator generate this in time.
/// </summary>
public partial class ClearanceRequestCheck
{

    [Attr]
    [JsonPropertyName("checkCode")]
    public string? CheckCode { get; set; }

    [Attr]
    [JsonPropertyName("departmentCode")]
    public string? DepartmentCode { get; set; }
}