//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Model.Cds;
public partial class ServiceHeader  //
{

    [Attr]
    [JsonPropertyName("sourceSystem")]
    public string? SourceSystem { get; set; }

    [Attr]
    [JsonPropertyName("destinationSystem")]
    public string? DestinationSystem { get; set; }

    [Attr]
    [JsonPropertyName("correlationId")]
    public string? CorrelationId { get; set; }

    [Attr]
    [JsonPropertyName("serviceCalled")]
    public DateTime? ServiceCalled { get; set; }

}