/*------------------------------------------------------------------------------
<auto-generated>
    This code was generated from the InternalClass template.
    Manual changes to this file may cause unexpected behavior in your application.
    Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
#nullable enable
using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;

namespace Btms.Model.Gvms;

/// <summary>
/// 
/// </summary>
public partial class GmrsByVrn //
{

    /// <summary>
    /// This is the identifier for a Vehicle Registration Number
    /// </summary>
    [Attr]
    [System.ComponentModel.Description("This is the identifier for a Vehicle Registration Number")]
    public string? Vrn { get; set; }
}
