//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Model.Gvms;
public partial class SearchGmrsForVRNrequest  //
{


    /// <summary>
    /// A list of VRN to search for GMRs.
    /// </summary>
    [Attr]
    [JsonPropertyName("vrns")]
    [System.ComponentModel.Description("A list of VRN to search for GMRs.")]
    public string[]? Vrns { get; set; }

}