/*------------------------------------------------------------------------------
<auto-generated>
    This code was generated from the InternalEnum template.
    Manual changes to this file may cause unexpected behavior in your application.
    Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Btms.Model.Ipaffs;

public enum FeedbackInformationAuthorityTypeEnum
{
    Exitbip,
    Finalbip,
    Localvetunit,
    Inspunit,
}
