//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Model.Ipaffs;

/// <summary>
/// Details of the risk categorisation level for a notification
/// </summary>
public partial class JourneyRiskCategorisationResult  //
{


    /// <summary>
    /// Risk Level is defined using enum values High,Medium,Low
    /// </summary>
    [Attr]
    [JsonPropertyName("riskLevel")]
    [System.ComponentModel.Description("Risk Level is defined using enum values High,Medium,Low")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public JourneyRiskCategorisationResultRiskLevelEnum? RiskLevel { get; set; }


    /// <summary>
    /// Indicator of whether the risk level was determined by the system or by the user
    /// </summary>
    [Attr]
    [JsonPropertyName("riskLevelMethod")]
    [System.ComponentModel.Description("Indicator of whether the risk level was determined by the system or by the user")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public JourneyRiskCategorisationResultRiskLevelMethodEnum? RiskLevelMethod { get; set; }


    /// <summary>
    /// The date and time the risk level has been set for a notification
    /// </summary>
    [Attr]
    [JsonPropertyName("riskLevelSetFor")]
    [System.ComponentModel.Description("The date and time the risk level has been set for a notification")]
    [Btms.Common.Json.UnknownTimeZoneDateTimeJsonConverter(nameof(RiskLevelSetFor)), MongoDB.Bson.Serialization.Attributes.BsonDateTimeOptions(Kind = DateTimeKind.Unspecified)]
    public DateTime? RiskLevelSetFor { get; set; }

}