//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Types.Alvs;

public partial class Items  //
{

    [JsonPropertyName("itemNumber")]
    public int? ItemNumber { get; set; }

    [JsonPropertyName("customsProcedureCode")]
    public string? CustomsProcedureCode { get; set; }

    [JsonPropertyName("taricCommodityCode")]
    public string? TaricCommodityCode { get; set; }

    [JsonPropertyName("goodsDescription")]
    public string? GoodsDescription { get; set; }

    [JsonPropertyName("consigneeId")]
    public string? ConsigneeId { get; set; }

    [JsonPropertyName("consigneeName")]
    public string? ConsigneeName { get; set; }

    [JsonPropertyName("itemNetMass")]
    public decimal? ItemNetMass { get; set; }

    [JsonPropertyName("itemSupplementaryUnits")]
    public decimal? ItemSupplementaryUnits { get; set; }

    [JsonPropertyName("itemThirdQuantity")]
    public decimal? ItemThirdQuantity { get; set; }

    [JsonPropertyName("itemOriginCountryCode")]
    public string? ItemOriginCountryCode { get; set; }

    [JsonPropertyName("documents")]
    public Document[]? Documents { get; set; }

    [JsonPropertyName("checks")]
    public Check[]? Checks { get; set; }

}