/*------------------------------------------------------------------------------
<auto-generated>
	This code was generated from the Enum template.
	Manual changes to this file may cause unexpected behavior in your application.
	Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Btms.Types.Gvms;

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum DirectionEnum
{
    [EnumMember(Value = "UK_INBOUND")]
    UkInbound,
    [EnumMember(Value = "UK_OUTBOUND")]
    UkOutbound,
    [EnumMember(Value = "GB_TO_NI")]
    GbToNi,
    [EnumMember(Value = "NI_TO_GB")]
    NiToGb,
}
