//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Types.Gvms;

/// <summary>
/// 
/// </summary>
public partial class SearchGmrsForDeclarationIdsrequest  //
{


    /// <summary>
    /// A list of declaration IDs to search for.  Currently, only customs and transit declaration IDs are accepted (DUCR, ERN or customs/transit MRN, depending on source system and crossing direction).
    /// </summary>
    [JsonPropertyName("declarationIds")]
    public string[]? DeclarationIds { get; set; }

}