//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Types.Ipaffs;

/// <summary>
/// Laboratory tests information details and information about laboratory that did the test
/// </summary>
public partial class Applicant  //
{


        /// <summary>
        /// Name of laboratory
        /// </summary>
    [JsonPropertyName("laboratory")]
        [Btms.SensitiveData.SensitiveData]
    public string? Laboratory { get; set; }

	
        /// <summary>
        /// Laboratory address
        /// </summary>
    [JsonPropertyName("laboratoryAddress")]
        [SensitiveData.SensitiveData]
    public string? LaboratoryAddress { get; set; }

	
        /// <summary>
        /// Laboratory identification
        /// </summary>
    [JsonPropertyName("laboratoryIdentification")]
        [SensitiveData.SensitiveData]
    public string? LaboratoryIdentification { get; set; }

	
        /// <summary>
        /// Laboratory phone number
        /// </summary>
    [JsonPropertyName("laboratoryPhoneNumber")]
        [SensitiveData.SensitiveData]
    public string? LaboratoryPhoneNumber { get; set; }

	
        /// <summary>
        /// Laboratory email
        /// </summary>
    [JsonPropertyName("laboratoryEmail")]
        [SensitiveData.SensitiveData]
    public string? LaboratoryEmail { get; set; }

	
        /// <summary>
        /// Sample batch number
        /// </summary>
    [JsonPropertyName("sampleBatchNumber")]
        [SensitiveData.SensitiveData]
    public string? SampleBatchNumber { get; set; }

	
        /// <summary>
        /// Type of analysis
        /// </summary>
    [JsonPropertyName("analysisType")]
    public ApplicantAnalysisTypeEnum? AnalysisType { get; set; }

	
        /// <summary>
        /// Number of samples analysed
        /// </summary>
    [JsonPropertyName("numberOfSamples")]
    public int? NumberOfSamples { get; set; }

	
        /// <summary>
        /// Type of sample
        /// </summary>
    [JsonPropertyName("sampleType")]
        [Btms.SensitiveData.SensitiveData]
    public string? SampleType { get; set; }

	
        /// <summary>
        /// Conservation of sample
        /// </summary>
    [JsonPropertyName("conservationOfSample")]
    public ApplicantConservationOfSampleEnum? ConservationOfSample { get; set; }

	
        /// <summary>
        /// inspector
        /// </summary>
    [JsonPropertyName("inspector")]
    public Inspector? Inspector { get; set; }

	
        /// <summary>
        /// Date the sample is taken
        /// </summary>
    [JsonPropertyName("sampleDate")]
    public DateOnly? SampleDate { get; set; }

	
        /// <summary>
        /// Time the sample is taken
        /// </summary>
    [JsonPropertyName("sampleTime")]
    public TimeOnly? SampleTime { get; set; }

	}


