//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Types.Ipaffs;


/// <summary>
/// Person to be contacted if there is an issue with the consignment
/// </summary>
public partial class ContactDetails  //
{


    /// <summary>
    /// Name of designated contact
    /// </summary>
    [JsonPropertyName("name")]
    [Btms.SensitiveData.SensitiveData]
    public string? Name { get; set; }


    /// <summary>
    /// Telephone number of designated contact
    /// </summary>
    [JsonPropertyName("telephone")]
    [Btms.SensitiveData.SensitiveData]
    public string? Telephone { get; set; }


    /// <summary>
    /// Email address of designated contact
    /// </summary>
    [JsonPropertyName("email")]
    [Btms.SensitiveData.SensitiveData]
    public string? Email { get; set; }


    /// <summary>
    /// Name of agent representing designated contact
    /// </summary>
    [JsonPropertyName("agent")]
    [Btms.SensitiveData.SensitiveData]
    public string? Agent { get; set; }

}