/*------------------------------------------------------------------------------
<auto-generated>
	This code was generated from the Enum template.
	Manual changes to this file may cause unexpected behavior in your application.
	Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Btms.Types.Ipaffs;

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum DecisionDecisionEnum
{
    [EnumMember(Value = "Non Acceptable")]
    NonAcceptable,
    [EnumMember(Value = "Acceptable for Internal Market")]
    AcceptableForInternalMarket,
    [EnumMember(Value = "Acceptable if Channeled")]
    AcceptableIfChanneled,
    [EnumMember(Value = "Acceptable for Transhipment")]
    AcceptableForTranshipment,
    [EnumMember(Value = "Acceptable for Transit")]
    AcceptableForTransit,
    [EnumMember(Value = "Acceptable for Temporary Import")]
    AcceptableForTemporaryImport,
    [EnumMember(Value = "Acceptable for Specific Warehouse")]
    AcceptableForSpecificWarehouse,
    [EnumMember(Value = "Acceptable for Private Import")]
    AcceptableForPrivateImport,
    [EnumMember(Value = "Acceptable for Transfer")]
    AcceptableForTransfer,
    [EnumMember(Value = "Horse Re-entry")]
    HorseReEntry,
}
