//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Btms.Types.Ipaffs;

/// <summary>
/// 
/// </summary>
public partial class IdentificationDetails  //
{


        /// <summary>
        /// Identification detail
        /// </summary>
    [JsonPropertyName("identificationDetail")]
        [Btms.SensitiveData.SensitiveData]
    public string? IdentificationDetail { get; set; }

	
        /// <summary>
        /// Identification description
        /// </summary>
    [JsonPropertyName("identificationDescription")]
        [Btms.SensitiveData.SensitiveData]
    public string? IdentificationDescription { get; set; }

	}


