/*------------------------------------------------------------------------------
<auto-generated>
	This code was generated from the Enum template.
	Manual changes to this file may cause unexpected behavior in your application.
	Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Btms.Types.Ipaffs;

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum MeansOfTransportTypeEnum
{
    [EnumMember(Value = "Aeroplane")]
    Aeroplane,
    [EnumMember(Value = "Road Vehicle")]
    RoadVehicle,
    [EnumMember(Value = "Railway Wagon")]
    RailwayWagon,
    [EnumMember(Value = "Ship")]
    Ship,
    [EnumMember(Value = "Other")]
    Other,
    [EnumMember(Value = "Road vehicle Aeroplane")]
    RoadVehicleAeroplane,
    [EnumMember(Value = "Ship Railway wagon")]
    ShipRailwayWagon,
    [EnumMember(Value = "Ship Road vehicle")]
    ShipRoadVehicle,
}
