/*------------------------------------------------------------------------------
<auto-generated>
	This code was generated from the Enum template.
	Manual changes to this file may cause unexpected behavior in your application.
	Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Btms.Types.Ipaffs;

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum PurposePurposeGroupEnum
{
    [EnumMember(Value = "For Import")]
    ForImport,
    [EnumMember(Value = "For NON-Conforming Consignments")]
    ForNONConformingConsignments,
    [EnumMember(Value = "For Transhipment to")]
    ForTranshipmentTo,
    [EnumMember(Value = "For Transit to 3rd Country")]
    ForTransitTo3rdCountry,
    [EnumMember(Value = "For Re-Import")]
    ForReImport,
    [EnumMember(Value = "For Private Import")]
    ForPrivateImport,
    [EnumMember(Value = "For Transfer To")]
    ForTransferTo,
    [EnumMember(Value = "For Import Re-Conformity Check")]
    ForImportReConformityCheck,
}
