name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

env:
  AWS_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: local
  AWS_SECRET_ACCESS_KEY: local
  
jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
           8.0
      - name: Check out code
        uses: actions/checkout@v3 
        
      - name: Verify Format
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "compose.yml"
          
      - name: Make Script Executable
        run: chmod +x ./start-localstack.sh

      - name: Create SNS/SQS
        run: ./start-localstack.sh
  
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
          mongodb-replica-set: test-rs
          mongodb-port: 29017

      - name: Make Script Executable
        run: chmod +x ./wait-for-docker-logs.sh

      - name: Wait for ASB Emulator
        run: |
          ./wait-for-docker-logs.sh servicebus-emulator "Emulator Service is Successfully Up" 60

      - name: Test
        run: dotnet test  --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" --collect:"XPlat Code Coverage" --results-directory ./coverage
        
      - name: install dotnet coverage
        run: dotnet tool install --global dotnet-coverage        
        
      - name: merge coverage reports
        run:  dotnet-coverage merge *.cobertura.xml --recursive --output merged.cobertura.xml --output-format cobertura
  
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: merged.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Generate OpenAPI specification
        run: make generate-openapi-spec

      - name: Save OpenApi specification
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: openapi.json

    ## SonarCloud
    ## Uncomment to unable SonarCloud scan
    ## Requires project to be set up in SonarCloud
    ## and the SonarCloud token to be set in the repository secrets
#   sonarcloud-scan:
#     name: CDP SonarCloud Scan
#     uses: ./.github/workflows/sonarcloud.yml
#     needs: pr-validator
#     secrets: inherit
