name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"
  HUSKY: 0

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and Publish
        uses: DEFRA/cdp-build-action/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate OpenAPI specification
        run: make generate-openapi-spec
      - name: Save OpenApi specification
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: openapi.json

  ## SonarCloud
  ## Uncomment to unable SonarCloud scan
  ## Requires project to be set up in SonarCloud
  ## and the SonarCloud token to be set in the repository secrets
#   sonarcloud-scan:
#     name: CDP SonarCloud Scan
#     uses: ./.github/workflows/sonarcloud.yml
#     needs: build
#     secrets: inherit
